trigger:
  name: todo-api-pr-trigger
  identifier: todoapi_pr_trigger
  enabled: true
  projectIdentifier: Demo_Quinto_Andar
  orgIdentifier: default
  pipelineIdentifier: todoapi_ci
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: PullRequest
        spec:
          connectorRef: org.Personal_GH
          autoAbortPreviousExecutions: true
          payloadConditions:
            - key: targetBranch
              operator: Equals
              value: main
          # Monorepo path filter: only trigger when files under apps/todo-api change
          pathFilters:
            - apps/todo-api/**
  inputYaml: |
    pipeline:
      identifier: todoapi_ci
      properties:
        ci:
          codebase:
            build:
              type: PR
              spec:
                number: <+trigger.prNumber>
